# Generated by Django 6.0.6 on 2026-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='temp',
            field=models.IntegerField(null=True),
        ),
    ]
