# Generated by Django 6.0.6 on 2026-07-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='temp',
        ),
    ]
