# Generated by Django 6.0.6 on 2026-07-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
