# Generated by Django 6.0.6 on 2026-08-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'can view history')]},
        ),
    ]
